set(_CATKIN_CURRENT_PACKAGE "msg_generate")
set(msg_generate_VERSION "0.0.0")
set(msg_generate_MAINTAINER "robit <robit@todo.todo>")
set(msg_generate_PACKAGE_FORMAT "2")
set(msg_generate_BUILD_DEPENDS "message_generation" "std_msgs")
set(msg_generate_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs")
set(msg_generate_BUILDTOOL_DEPENDS "catkin")
set(msg_generate_BUILDTOOL_EXPORT_DEPENDS )
set(msg_generate_EXEC_DEPENDS "message_runtime" "std_msgs")
set(msg_generate_RUN_DEPENDS "message_runtime" "std_msgs")
set(msg_generate_TEST_DEPENDS )
set(msg_generate_DOC_DEPENDS )
set(msg_generate_URL_WEBSITE "")
set(msg_generate_URL_BUGTRACKER "")
set(msg_generate_URL_REPOSITORY "")
set(msg_generate_DEPRECATED "")