# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/robit/catkin_ws/src/msg_generate/msg/pan_tilt_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/imu_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/motion_end.msg;/home/robit/catkin_ws/src/msg_generate/msg/serial_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/Motor_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/motionNum_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/ikcoordinate_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/position_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/ik_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/ikend_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/yaw_set.msg;/home/robit/catkin_ws/src/msg_generate/msg/support_onestep_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/Mt2Serial_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/tune2walk.msg;/home/robit/catkin_ws/src/msg_generate/msg/zmp_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/localization_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/robocupcontroller.msg;/home/robit/catkin_ws/src/msg_generate/msg/robocupvision.msg;/home/robit/catkin_ws/src/msg_generate/msg/udp_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/udp_order.msg;/home/robit/catkin_ws/src/msg_generate/msg/eom_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/angle2.msg;/home/robit/catkin_ws/src/msg_generate/msg/wheel_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/Motion_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/Step_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/Running_2020_vision.msg;/home/robit/catkin_ws/src/msg_generate/msg/motion_stop.msg;/home/robit/catkin_ws/src/msg_generate/msg/Local_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/Local_Info.msg;/home/robit/catkin_ws/src/msg_generate/msg/scv_vision.msg;/home/robit/catkin_ws/src/msg_generate/msg/walk_pattern.msg;/home/robit/catkin_ws/src/msg_generate/msg/kuro_cotton_candy.msg;/home/robit/catkin_ws/src/msg_generate/msg/master2hanoi_vision2019msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/Serial2LC_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/L_LC_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/R_LC_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/com_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/ik_angle_sim.msg;/home/robit/catkin_ws/src/msg_generate/msg/localv2_msg.msg;/home/robit/catkin_ws/src/msg_generate/msg/motion_balance.msg;/home/robit/catkin_ws/src/msg_generate/msg/udp_msg_TC_Helper.msg;/home/robit/catkin_ws/src/msg_generate/msg/udp_msg_TC_Kicker.msg;/home/robit/catkin_ws/src/msg_generate/msg/Motor_msg_pt.msg"
services_str = ""
pkg_name = "msg_generate"
dependencies_str = "std_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "msg_generate;/home/robit/catkin_ws/src/msg_generate/msg;std_msgs;/opt/ros/melodic/share/std_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python2"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/melodic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
